version: 2.1

orbs:
  architect: giantswarm/architect@4.14.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: aws-attach-etcd-dep
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/aws-attach-etcd-dep"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/aws-attach-etcd-dep"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/aws-attach-etcd-dep"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^v.*/